name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions 🚀
on: [push]

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 1. 查询目标仓库最新Release
      - name: Get latest release of target repo
        id: get_remote_release
        run: |
          # 获取最新release tag名称
          LATEST_TAG=$(gh api repos/apache/rocketmq/releases/latest --jq '.tag_name')
          echo "REMOTE_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest remote version: $LATEST_TAG"
