name: Github Actions Demo
on: [push]
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 1. 查询目标仓库最新Release
      - name: Get latest release of target repo
        id: get_remote_release
        run: |
          # 获取apache/rocketmq最新release
          RAW_TAG=$(gh api repos/apache/rocketmq/releases/latest --jq '.tag_name')
          LATEST_TAG=$(echo "$RAW_TAG" | sed -E 's/^[^0-9]+//')
          echo "REMOTE_RAW_TAG=$RAW_TAG" >> $GITHUB_ENV
          echo "REMOTE_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest remote: tag: $RAW_TAG, version: $LATEST_TAG"

      # 2. 查询本仓库最新Release
      - name: Read self laste version
        id: read_last
        run: |
          # 获取apache/rocketmq最新release
          LATEST_TAG=$(gh api repos/ouchonghui/rocketmq-docker/releases/latest --jq '.tag_name')
          echo "SELF_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest self tag: $LATEST_TAG"
