name: Github Actions Demo
on:
  workflow_dispatch:
  schedule:
    # 每天 UTC 13:37（北京时间 21:37）检查一次
    - cron: '37 13 * * *'
env:
  GH_TOKEN: ${{ github.token }}
  

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 1. 查询目标仓库最新Release
      - name: Get latest release of target repo
        id: get_remote_release
        run: |
          # 获取apache/rocketmq最新release
          RAW_TAG=$(gh api repos/apache/rocketmq/releases/latest --jq '.tag_name')
          LATEST_TAG=$(echo "$RAW_TAG" | sed -E 's/^[^0-9]+//')
          echo "REMOTE_RAW_TAG=$RAW_TAG" >> $GITHUB_ENV
          echo "REMOTE_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest remote: tag: $RAW_TAG, version: $LATEST_TAG"

      # 2. 查询本仓库最新Release
      - name: Get latest release of self repo
        id: read_last
        run: |
          # 获取apache/rocketmq最新release
          LATEST_TAG=$(gh api repos/ouchonghui/test_actions/releases/latest --jq '.tag_name')
          echo "SELF_LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest self tag: $LATEST_TAG"

      # 3. 判断版本是否一致，相同则直接终止流程
      - name: Skip if version unchanged
        if: env.REMOTE_LATEST_TAG == env.SELF_LATEST_TAG
        run: |
          echo "版本未更新，当前最新版本 rocketmq-all-${{ env.REMOTE_LATEST_TAG }} 与本地记录一致，无需发布，退出流程"

      # 4. 版本有更新
      - name: Compare version & build if new
        if: env.REMOTE_LATEST_TAG != env.SELF_LATEST_TAG
        run: |
          echo "发现新版本 ${{ env.REMOTE_LATEST_TAG }}，开始构建打包"

      # 5. 自动创建Release发布
      - name: Create new release in current repo
        if: env.REMOTE_LATEST_TAG != env.SELF_LATEST_TAG
        run: |
          gh release create ${{ env.REMOTE_LATEST_TAG }} \
            --title "Auto Sync Release rocketmq-all-${{ env.REMOTE_LATEST_TAG }}" \
            --notes "Auto generated by GitHub Action, sync with apache/rocketmq latest release"
